### ISSUE TITLE
CREST2 - api data mCarFlags

### ISSUE THREAD

**Issue by hoserpa** [viper4gh/CREST2#5]
Hi, I'm using your API (great job).

The problem is when using the mCarFlags data, which always returns 2.

I try to use it for the pit limit, but it never changes to that state.

Is there a special way to use it or is it just an API bug?

If you could help me, please.

Regards

**Comment by viper4gh** [comment]
I think this is an API bug.
https://github.com/viper4gh/CREST2/blob/master/SharedMemoryRenderer.cpp#L139
At this point I push the value from SharedMemory directly into a string without any conversion or something else.
Further "2" is a valid value. If there was something wrong here, I'd expect something silly, like empty string or a complete crazy value.
And mCarFlags is no new variable in pcars2. There was no change since pcars1. This means CREST1 from Lars works the same way, because I added the new variables of pcars2 only and didn't touch any of the old variables. 
Maybe you can test with CREST1 (https://cars-rest-api.com/#downloads) and pcars2 in pcars1 SharedMemory Mode, but I think if there is a bug, it is the same problem then.
But if you have pcars1 you can test it with CREST1. If it works, it will be definitely a bug in pcars2.

**Comment by viper4gh** [comment]
I tested it in game.
Private Training with an Acura NSX GT3.
At session start mCarFlags was 10 in CREST2.
If I switch the Headlights on, it is 11. Switching off, 10 again.
But switching the pit limiter on/off changes nothing.
It is definitely a game API bug.
